# **PYTHON BASICS PROGRAMMING ASSIGNMENT 8**

**Manisha Singh**

**Q1. Write a Python Program to Add Two Matrices.**

In [2]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

summat = np.add(mat1, mat2)
print(f"Sum: {summat}")

Sum: [[ 3  5  8]
 [ 9 11 13]
 [15 17 10]]


**Q2. Write a Python Program to Multiply Two Matrices.**

In [3]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

prod = np.dot(mat1, mat2)
print(f"Product: {prod}")

Product: [[ 44  51  22]
 [ 81  96  57]
 [126 150  93]]


**Q3. Write a Python Program to Transpose a Matrix.**

In [4]:
a = [[1,2,3],[4,5,6],[7,8,9]]

def transpose(in_matrix):
    out_matrix = []

    for ele in range(len(in_matrix[0])):
        out_matrix.append([0 for i in range(len(in_matrix))])

    for i in range(len(in_matrix)):
        for j in range(len(in_matrix[i])):
            out_matrix[j][i] = in_matrix[i][j]

    print(f'Before transpose: {in_matrix} \nAfter transpose: {out_matrix}')
        
transpose(a)

Before transpose: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
After transpose: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]


**Q4. Write a Python Program to Sort Words in Alphabetic Order.**

In [7]:
def sortstring():
    string = input("Enter the String: ").lower()
    sorted_list = sorted(string.split(' '))
    print(' '.join(sorted_list))

sortstring()

end here is the


**Q5. Write a Python Program to Remove Punctuation From a String.**

In [8]:
def removepunctuations():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter the string: ')
    out_string = ''

    for ele in in_string:
        if ele not in punctuations:
            out_string += ele

    print(out_string)
    
removepunctuations()

Oh my god 
